//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaElectrodomesticos.Core.Repositories.Implementations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedureNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentaElectrodomesticos.Core.Repositories.Implementations.StoredProcedureNames", typeof(StoredProcedureNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddCliente.
        /// </summary>
        internal static string AddCliente {
            get {
                return ResourceManager.GetString("AddCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddEmpleado.
        /// </summary>
        internal static string AddEmpleado {
            get {
                return ResourceManager.GetString("AddEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddFactura.
        /// </summary>
        internal static string AddFactura {
            get {
                return ResourceManager.GetString("AddFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddFacturaPago.
        /// </summary>
        internal static string AddFacturaPago {
            get {
                return ResourceManager.GetString("AddFacturaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddFacturaProducto.
        /// </summary>
        internal static string AddFacturaProducto {
            get {
                return ResourceManager.GetString("AddFacturaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddProducto.
        /// </summary>
        internal static string AddProducto {
            get {
                return ResourceManager.GetString("AddProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddRol.
        /// </summary>
        internal static string AddRol {
            get {
                return ResourceManager.GetString("AddRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddStock.
        /// </summary>
        internal static string AddStock {
            get {
                return ResourceManager.GetString("AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.AddUsuario.
        /// </summary>
        internal static string AddUsuario {
            get {
                return ResourceManager.GetString("AddUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetCategorias.
        /// </summary>
        internal static string GetCategorias {
            get {
                return ResourceManager.GetString("GetCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetCliente.
        /// </summary>
        internal static string GetCliente {
            get {
                return ResourceManager.GetString("GetCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetClientes.
        /// </summary>
        internal static string GetClientes {
            get {
                return ResourceManager.GetString("GetClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetClientesByFiltros.
        /// </summary>
        internal static string GetClientesByFiltros {
            get {
                return ResourceManager.GetString("GetClientesByFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetClientesPremium.
        /// </summary>
        internal static string GetClientesPremium {
            get {
                return ResourceManager.GetString("GetClientesPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetEmpleado.
        /// </summary>
        internal static string GetEmpleado {
            get {
                return ResourceManager.GetString("GetEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetEmpleadoFiltros.
        /// </summary>
        internal static string GetEmpleadoFiltros {
            get {
                return ResourceManager.GetString("GetEmpleadoFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetEmpleados.
        /// </summary>
        internal static string GetEmpleados {
            get {
                return ResourceManager.GetString("GetEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetEmpleadosByFiltros.
        /// </summary>
        internal static string GetEmpleadosByFiltros {
            get {
                return ResourceManager.GetString("GetEmpleadosByFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetEmpleadosWithoutUsuarios.
        /// </summary>
        internal static string GetEmpleadosWithoutUsuarios {
            get {
                return ResourceManager.GetString("GetEmpleadosWithoutUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetFactura.
        /// </summary>
        internal static string GetFactura {
            get {
                return ResourceManager.GetString("GetFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetFacturasImpagas.
        /// </summary>
        internal static string GetFacturasImpagas {
            get {
                return ResourceManager.GetString("GetFacturasImpagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetFuncionalidades.
        /// </summary>
        internal static string GetFuncionalidades {
            get {
                return ResourceManager.GetString("GetFuncionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetMarcas.
        /// </summary>
        internal static string GetMarcas {
            get {
                return ResourceManager.GetString("GetMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetMejoresCategorias.
        /// </summary>
        internal static string GetMejoresCategorias {
            get {
                return ResourceManager.GetString("GetMejoresCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetPermisosByUsuario.
        /// </summary>
        internal static string GetPermisosByUsuario {
            get {
                return ResourceManager.GetString("GetPermisosByUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProducto.
        /// </summary>
        internal static string GetProducto {
            get {
                return ResourceManager.GetString("GetProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProductos.
        /// </summary>
        internal static string GetProductos {
            get {
                return ResourceManager.GetString("GetProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProductosByFiltros.
        /// </summary>
        internal static string GetProductosByFiltros {
            get {
                return ResourceManager.GetString("GetProductosByFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProductoStocks.
        /// </summary>
        internal static string GetProductoStocks {
            get {
                return ResourceManager.GetString("GetProductoStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProductoStocksBySucursal.
        /// </summary>
        internal static string GetProductoStocksBySucursal {
            get {
                return ResourceManager.GetString("GetProductoStocksBySucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetProvincias.
        /// </summary>
        internal static string GetProvincias {
            get {
                return ResourceManager.GetString("GetProvincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetRol.
        /// </summary>
        internal static string GetRol {
            get {
                return ResourceManager.GetString("GetRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetRoles.
        /// </summary>
        internal static string GetRoles {
            get {
                return ResourceManager.GetString("GetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetRolesByFiltros.
        /// </summary>
        internal static string GetRolesByFiltros {
            get {
                return ResourceManager.GetString("GetRolesByFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetRolesByUsuario.
        /// </summary>
        internal static string GetRolesByUsuario {
            get {
                return ResourceManager.GetString("GetRolesByUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetSucuralFiltros.
        /// </summary>
        internal static string GetSucuralFiltros {
            get {
                return ResourceManager.GetString("GetSucuralFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetSucursales.
        /// </summary>
        internal static string GetSucursales {
            get {
                return ResourceManager.GetString("GetSucursales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetTableroControl.
        /// </summary>
        internal static string GetTableroControl {
            get {
                return ResourceManager.GetString("GetTableroControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetUsuario.
        /// </summary>
        internal static string GetUsuario {
            get {
                return ResourceManager.GetString("GetUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetUsuarioByUsername.
        /// </summary>
        internal static string GetUsuarioByUsername {
            get {
                return ResourceManager.GetString("GetUsuarioByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetUsuarios.
        /// </summary>
        internal static string GetUsuarios {
            get {
                return ResourceManager.GetString("GetUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.GetUsuariosByFiltros.
        /// </summary>
        internal static string GetUsuariosByFiltros {
            get {
                return ResourceManager.GetString("GetUsuariosByFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetEnableCliente.
        /// </summary>
        internal static string SetEnableCliente {
            get {
                return ResourceManager.GetString("SetEnableCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetEnableEmpleado.
        /// </summary>
        internal static string SetEnableEmpleado {
            get {
                return ResourceManager.GetString("SetEnableEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetEnableProducto.
        /// </summary>
        internal static string SetEnableProducto {
            get {
                return ResourceManager.GetString("SetEnableProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetEnableRol.
        /// </summary>
        internal static string SetEnableRol {
            get {
                return ResourceManager.GetString("SetEnableRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetEnableUsuario.
        /// </summary>
        internal static string SetEnableUsuario {
            get {
                return ResourceManager.GetString("SetEnableUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.SetUsuarioIntentos.
        /// </summary>
        internal static string SetUsuarioIntentos {
            get {
                return ResourceManager.GetString("SetUsuarioIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.UpdateCliente.
        /// </summary>
        internal static string UpdateCliente {
            get {
                return ResourceManager.GetString("UpdateCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.UpdateEmpleado.
        /// </summary>
        internal static string UpdateEmpleado {
            get {
                return ResourceManager.GetString("UpdateEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.UpdateProducto.
        /// </summary>
        internal static string UpdateProducto {
            get {
                return ResourceManager.GetString("UpdateProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.UpdateRol.
        /// </summary>
        internal static string UpdateRol {
            get {
                return ResourceManager.GetString("UpdateRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOTNETPY.UpdateUsuario.
        /// </summary>
        internal static string UpdateUsuario {
            get {
                return ResourceManager.GetString("UpdateUsuario", resourceCulture);
            }
        }
    }
}
