//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaElectrodomesticos.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VentaElectrodomesticos.Core.Resources.MessageProvider", typeof(MessageProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta realizada exitosamente..
        /// </summary>
        public static string AltaExitosa {
            get {
                return ResourceManager.GetString("AltaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago se registro de manera exitosa..
        /// </summary>
        public static string AltaPagoExitoso {
            get {
                return ResourceManager.GetString("AltaPagoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado y la aplicación va a cerrarse..
        /// </summary>
        public static string CatastrophicError {
            get {
                return ResourceManager.GetString("CatastrophicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede dar de alta un empleado como cliente..
        /// </summary>
        public static string ClienteIsEmpleado {
            get {
                return ResourceManager.GetString("ClienteIsEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error inesperado con la base de datos. Por favor avisele al administrador de sistemas. La aplicación va a cerrarse..
        /// </summary>
        public static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        public static string Dni {
            get {
                return ResourceManager.GetString("Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado fue dado de baja..
        /// </summary>
        public static string EmpleadoConBaja {
            get {
                return ResourceManager.GetString("EmpleadoConBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar el cliente porque se encuentra deshabilitado..
        /// </summary>
        public static string ErrorUpdateClienteDisabled {
            get {
                return ResourceManager.GetString("ErrorUpdateClienteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar el empleado porque se encuentra deshabilitado..
        /// </summary>
        public static string ErrorUpdateEmpleadoDisabled {
            get {
                return ResourceManager.GetString("ErrorUpdateEmpleadoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar el producto porque se encuentra deshabilitado..
        /// </summary>
        public static string ErrorUpdateProductoDisabled {
            get {
                return ResourceManager.GetString("ErrorUpdateProductoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar el rol porque se encuentra deshabilitado..
        /// </summary>
        public static string ErrorUpdateRolDisabled {
            get {
                return ResourceManager.GetString("ErrorUpdateRolDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede actualizar el usuario porque se encuentra deshabilitado..
        /// </summary>
        public static string ErrorUpdateUsuarioDisabled {
            get {
                return ResourceManager.GetString("ErrorUpdateUsuarioDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente ya esta cargado en el sistema..
        /// </summary>
        public static string ExistCliente {
            get {
                return ResourceManager.GetString("ExistCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado ya esta cargado en el sistema..
        /// </summary>
        public static string ExistEmpleado {
            get {
                return ResourceManager.GetString("ExistEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura no existe en el sistema..
        /// </summary>
        public static string FacturaNotExist {
            get {
                return ResourceManager.GetString("FacturaNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La factura ya esta pagada..
        /// </summary>
        public static string FacturaPaid {
            get {
                return ResourceManager.GetString("FacturaPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una factura..
        /// </summary>
        public static string FacturaRequired {
            get {
                return ResourceManager.GetString("FacturaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede confirmar la factura porque no tiene productos..
        /// </summary>
        public static string FacturaWithoutProductos {
            get {
                return ResourceManager.GetString("FacturaWithoutProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionalidades.
        /// </summary>
        public static string Funcionalidades {
            get {
                return ResourceManager.GetString("Funcionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar/Deshabilitar.
        /// </summary>
        public static string HabilitarDeshabilitar {
            get {
                return ResourceManager.GetString("HabilitarDeshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad requerida es mayor al stock disponible en la sucursal seleccionada..
        /// </summary>
        public static string InsufficientStockAvalability {
            get {
                return ResourceManager.GetString("InsufficientStockAvalability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una cantidad de stock válida para realizar esta operacion..
        /// </summary>
        public static string InvalidCantidad {
            get {
                return ResourceManager.GetString("InvalidCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de cuotas a pagar es mayor a las cuotas restantes en la factura..
        /// </summary>
        public static string InvalidCuotas {
            get {
                return ResourceManager.GetString("InvalidCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas ingresadas no coinciden..
        /// </summary>
        public static string InvalidInputPasswordConfirmation {
            get {
                return ResourceManager.GetString("InvalidInputPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificación realizada exitosamente..
        /// </summary>
        public static string ModificacionExitosa {
            get {
                return ResourceManager.GetString("ModificacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demasiados intentos de inicio de sesión fallidos. Usuario Inhabilitado..
        /// </summary>
        public static string MuchosIntentosBlock {
            get {
                return ResourceManager.GetString("MuchosIntentosBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los empleados tienen un usuario en el sistema. No se puede realizar el alta..
        /// </summary>
        public static string NoEmpleadosWithoutUsuarios {
            get {
                return ResourceManager.GetString("NoEmpleadosWithoutUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto no tiene stock en la sucursal seleccionada..
        /// </summary>
        public static string NoStockAvalability {
            get {
                return ResourceManager.GetString("NoStockAvalability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar porque esta deshabilitada para realizar operaciones..
        /// </summary>
        public static string NoUpdateDisabledEntity {
            get {
                return ResourceManager.GetString("NoUpdateDisabledEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta..
        /// </summary>
        public static string PasswordInvalido {
            get {
                return ResourceManager.GetString("PasswordInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El precio ingresado es inválido..
        /// </summary>
        public static string PrecioInvalido {
            get {
                return ResourceManager.GetString("PrecioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Producto {
            get {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto ya fue agregado a la lista..
        /// </summary>
        public static string ProductoAdded {
            get {
                return ResourceManager.GetString("ProductoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto no existe en el sistema..
        /// </summary>
        public static string ProductoNotExist {
            get {
                return ResourceManager.GetString("ProductoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursal.
        /// </summary>
        public static string Sucursal {
            get {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Empleado.
        /// </summary>
        public static string TipoEmpleado {
            get {
                return ResourceManager.GetString("TipoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya esta en uso por otro usuario..
        /// </summary>
        public static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario inválido..
        /// </summary>
        public static string UsernameInvalido {
            get {
                return ResourceManager.GetString("UsernameInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario fue dado de baja..
        /// </summary>
        public static string UsuarioConBaja {
            get {
                return ResourceManager.GetString("UsuarioConBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario está inhabilitado para iniciar sesión..
        /// </summary>
        public static string UsuarioInhabilitadoInicioSesion {
            get {
                return ResourceManager.GetString("UsuarioInhabilitadoInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene permisos asignados..
        /// </summary>
        public static string UsuarioSinPermisos {
            get {
                return ResourceManager.GetString("UsuarioSinPermisos", resourceCulture);
            }
        }
    }
}
